# Generated by Django 3.0.8 on 2020-07-27 18:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 7, 27, 18, 13, 5, 509282, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='TodoEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 7, 27, 18, 13, 5, 509282, tzinfo=utc))),
                ('is_done', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.Category')),
            ],
        ),
    ]
