# Generated by Django 3.0.8 on 2020-07-27 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 18, 13, 12, 470663, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoentry',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 18, 13, 12, 470663, tzinfo=utc)),
        ),
    ]
