# Generated by Django 3.0.8 on 2020-07-27 18:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200727_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoentry',
            options={'ordering': ['created_date']},
        ),
        migrations.AddField(
            model_name='todoentry',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 18, 34, 9, 542878, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoentry',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 18, 34, 9, 542878, tzinfo=utc)),
        ),
    ]
